import Features from '@/components/about/Features'
import Layout from '@/layout'
import { Box, Container, Heading } from '@chakra-ui/react'
import Head from 'next/head'

export default function Page() {
  return (
    <>
      <Head>
        <title>BTC2USDT</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Box
          bgColor={'green.100'}
          pt={{ base: 8, md: 20 }}
          pb={{ base: 16, md: 32 }}>
          <Container maxW={'container.xl'}>
            <Heading
              fontWeight={600}
              fontSize={{ base: '2xl', sm: '4xl', md: '6xl' }}>
              About Us
              <br />
            </Heading>
          </Container>
        </Box>
        <Box pt={{ base: 8, md: 20 }} pb={{ base: 16, md: 32 }}>
          <Container maxW={'container.xl'}>
            <Features />
          </Container>
        </Box>
      </main>
    </>
  )
}

Page.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>
}
