import About from '@/components/home/About'
import Explain from '@/components/home/Explain'
import Featured from '@/components/home/Featured'
import Pairing from '@/components/home/Pairing'
import Testimonials from '@/components/Testimonials'
import Layout from '@/layout'
import Footer from '@/layout/Footer'
import Header from '@/layout/Header'
import Hero from '@/layout/Hero'
import { Box, Text } from '@chakra-ui/react'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next next</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Hero />
        <Featured />
        <Pairing />
        <About />
        <Testimonials />
      </main>
    </>
  )
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>
}
