import {
  Box,
  Button,
  Container,
  Editable,
  EditableInput,
  EditablePreview,
  Heading,
  Text
} from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'
import { useQRCode } from 'next-qrcode'

const StepTwo = () => {
  const { Canvas } = useQRCode()
  return (
    <>
      <Head>
        <title>Create Next next</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Box bg='green.100' py={'20'}>
          <Container maxW={'container.xl'}>
            <Heading
              fontWeight={600}
              fontSize={{ base: '2xl', sm: '4xl', md: '6xl' }}>
              Waiting for your Chainlink <br />
            </Heading>
            <Heading as='h4' size='md' color='blackAlpha.700' my={6}>
              Transfer 100.00000000 Chainlink to this address:
            </Heading>
            <Text fontSize={'xl'} p={2} border='2px' borderColor={'green.600'}>
              0xf6d3e2a6ad525fea8ad8ae0b3c5608143aa332e2
            </Text>
            <Box py={4}>
              <Canvas
                text={'0xf6d3e2a6ad525fea8ad8ae0b3c5608143aa332e2'}
                options={{
                  level: 'M',
                  margin: 3,
                  scale: 4,
                  width: 200,
                  color: {
                    dark: '#000',
                    light: '#FFF'
                  }
                }}
              />
            </Box>

            <Text fontSize={'xl'} py={2}>
              Please verify that the wallet address you provided is correct
              before transfering the coins, as the transaction cannot be
              canceled once you transfer the coins.
            </Text>
            <Text fontSize={'xl'} py={2}>
              Once you transfer the coins and the network has confirmed the
              transaction, the exchanged coins will be sent to the address you
              provided: 1Lbcfr7sAHTD9CgdQo3HTMTkV8LK4ZnX71
            </Text>
            <Button size={'lg'} colorScheme='green' my='5'>
              Yes! I have now transfered the coins
            </Button>
          </Container>
        </Box>
      </main>
    </>
  )
}

export default StepTwo
